services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
      - "35729:35729"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    # ... (mantenha igual ao anterior)
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev: